package com.fr.factoryclicker.resources;

public enum ResourceType {
    IRON_ORE, COPPER_ORE, LIMESTONE, COAL, CRUDE_OIL, CATERIUM_ORE, RAW_QUARTZ, BAUXITE,

    CABLE, CONCRETE, COPPER_INGOT, IRON_INGOT, IRON_PLATE, IRON_ROD, SCREW, WIRE,
    CATERIUM_INGOT, QUICKWIRE, QUARTZ_CRYSTAL, SILICA, STEEL_BEAM, STEEL_PIPE,
    PLASTIC, RUBBER,

    REINFORCED_IRON_PLATE, MODULAR_FRAME, ROTOR, ENCASED_INDUSTRIAL_BEAM, MOTOR,
    STATOR, STEEL_INGOT, AI_LIMITER, CIRCUIT_BOARD, ALUMINIUM_INGOT,
    ALUMINIUM_SHEET, HEAT_SINK,

    CRYSTAL_OSCILLATOR, HIGH_SPEED_CONNECTOR,

    HEAVY_MODULAR_FRAME, COMPUTER, SUPERCOMPUTER, RADIO_CONTROL_UNIT, TURBO_MOTOR;
}
